<Project Sdk="Microsoft.NET.Sdk">

  <!-- Core module for Dark Souls III -->
  <Import Project="..\..\Shared\Core.props" />

  <PropertyGroup>
    <Version>0.1.3</Version>
    <Product>Dynamic Key Prompts for Dark Souls III</Product>
    <Description>Shows the keys you actually bound in Dark Souls III button prompts.</Description>
  </PropertyGroup>

</Project>
